{% set version = "5.0.2" %}

package:
  name: dask-labextension
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask_labextension/dask_labextension-{{ version }}.tar.gz
  sha256: 3c6b9948e2cdc167b63e74aa695667c00e0591a7779af025cb3cbabbe49e5afa

build:
  number: 0
  noarch: python

outputs:
  - name: dask-labextension
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python >=3.6
        - pip
        - nodejs >=12
        - jupyter-packaging >=0.7.0,<0.8
      run:
        - python >=3.6
        - bokeh >=1.0.0,!=2.0.0
        - distributed >=1.24.1
        - jupyter-server-proxy >=1.3.2
        - jupyterlab >=3.0.0
    test:
      imports:
        - dask_labextension
      requires:
        - pip
      commands:
        - pip check

  - name: dask_labextension
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('dask-labextension', max_pin="x.x.x") }}
    test:
      imports:
        - dask_labextension

about:
  home: https://github.com/dask/dask-labextension
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter Notebook server extension manages Dask clusters

extra:
  recipe-maintainers:
    - xhochy
    - ocefpaf
    - jsignell
