{% set version = "7.0.0" %}

package:
  name: dask-labextension
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask_labextension/dask_labextension-{{ version }}.tar.gz
  sha256: 45a60bd0ad31c5e425986b7e40a5aa242aa582ea868025ac2b82d0aa16ffcb8a

build:
  number: 0
  noarch: python

outputs:
  - name: dask-labextension
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python >=3.6
        - pip
        - jupyter-packaging
      run:
        - python >=3.6
        - bokeh >=1.0.0,!=2.0.0
        - distributed >=1.24.1
        - jupyter-server-proxy >=1.3.2
        - jupyterlab >=3.0.0
    test:
      imports:
        - dask_labextension
      requires:
        - pip
      commands:
        - pip check
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - cat labextensions | grep "dask-labextension.*OK.*dask_labextension"  # [unix]
        - dir %PREFIX%\share\jupyter\labextensions\dask-labextension\schemas\dask-labextension\plugin.json || exit 1  # [win]
        - ls ${PREFIX}/share/jupyter/labextensions/dask-labextension/schemas/dask-labextension/plugin.json  # [not win]

  - name: dask_labextension
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('dask-labextension', max_pin="x.x.x") }}
    test:
      imports:
        - dask_labextension

about:
  home: https://github.com/dask/dask-labextension
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - dask_labextension/labextension/static/third-party-licenses.json
  summary: A JupyterLab extension for Dask.

extra:
  recipe-maintainers:
    - xhochy
    - ocefpaf
    - jsignell
    - bollwyvl
